# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-16 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('actor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'actor',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.IntegerField(db_column='category_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('store_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=50)),
                ('address_id', models.IntegerField()),
                ('active', models.IntegerField()),
                ('create_date', models.DateTimeField()),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('film_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('release_year', models.CharField(max_length=4)),
                ('original_language_id', models.IntegerField()),
                ('rental_duration', models.IntegerField()),
                ('rental_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('length', models.IntegerField()),
                ('replacement_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rating', models.CharField(choices=[('G', 'General'), ('PG', 'Parental Guidance'), ('PG-13', 'Parental Guidance 13'), ('R', 'Rated'), ('NC-17', 'NC-17')], max_length=5)),
                ('special_features', models.TextField()),
            ],
            options={
                'db_table': 'film',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('language_id', models.IntegerField(db_column='language_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'language',
            },
        ),
        migrations.CreateModel(
            name='ActorInfo',
            fields=[
                ('actor_id', models.OneToOneField(db_column='actor_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sakila.Actor')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('film_info', models.TextField()),
            ],
            options={
                'db_table': 'actor_info',
            },
        ),
        migrations.CreateModel(
            name='FilmActor',
            fields=[
                ('film_id', models.OneToOneField(db_column='film_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='actors_url', serialize=False, to='sakila.Film')),
                ('actor_id', models.ForeignKey(db_column='actor_id', on_delete=django.db.models.deletion.CASCADE, related_name='films', to='sakila.Actor')),
            ],
            options={
                'db_table': 'film_actor',
            },
        ),
        migrations.CreateModel(
            name='FilmCategory',
            fields=[
                ('film_id', models.OneToOneField(db_column='film_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='category_url', serialize=False, to='sakila.Film')),
                ('category_id', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, to='sakila.Category')),
            ],
            options={
                'db_table': 'film_category',
            },
        ),
        migrations.AddField(
            model_name='film',
            name='language_url',
            field=models.OneToOneField(db_column='language_id', on_delete=django.db.models.deletion.CASCADE, to='sakila.Language'),
        ),
    ]
